## Disease Diagnosis:

## Preprocessing Data

In [1]:

import pandas as pd
df1= pd.read_csv("symtoms_df.csv")

In [2]:
df1

Unnamed: 0                                  Disease  \
0              0                         Fungal infection   
1              1                         Fungal infection   
2              2                         Fungal infection   
3              3                         Fungal infection   
4              4                         Fungal infection   
...          ...                                      ...   
4915        4915  (vertigo) Paroymsal  Positional Vertigo   
4916        4916                                     Acne   
4917        4917                  Urinary tract infection   
4918        4918                                Psoriasis   
4919        4919                                 Impetigo   

                 Symptom_1              Symptom_2              Symptom_3  \
0                  itching              skin_rash   nodal_skin_eruptions   
1                skin_rash   nodal_skin_eruptions    dischromic _patches   
2                  itching   nodal_skin_eruptions    dischromic _patches   
3                  itching              skin_rash    dischromic _patches   
4                  itching              skin_rash   nodal_skin_eruptions   
...                    ...                    ...                    ...   
4915              vomiting               headache                 nausea   
4916             skin_rash     pus_filled_pimples             blackheads   
4917   burning_micturition     bladder_discomfort    foul_smell_of urine   
4918             skin_rash             joint_pain           skin_peeling   
4919             skin_rash             high_fever                blister   

                      Symptom_4  
0           dischromic _patches  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
...                         ...  
4915         spinning_movements  
4916                   scurring  
4917   continuous_feel_of_urine  
4918        silver_like_dusting  
4919       red_sore_around_nose  

[4920 rows x 6 columns]

In [3]:
import pandas as pd

df= pd.read_json("hf://datasets/fhai50032/Symptoms_to_disease_7k/Symptoms_to_disease_7k.json")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [4]:
df

query  \
0     System:'You are a highly qualified doctor.and ...   
1     System:'You are a highly qualified doctor.and ...   
2     System:'You are a highly qualified doctor.and ...   
3     System:'You are a highly qualified doctor.and ...   
4     System:'You are a highly qualified doctor.and ...   
...                                                 ...   
7038  System:'You are a highly qualified doctor.and ...   
7039  System:'You are a highly qualified doctor.and ...   
7040  System:'You are a highly qualified doctor.and ...   
7041  System:'You are a highly qualified doctor.and ...   
7042  System:'You are a highly qualified doctor.and ...   

                                       response  
0                         You may have Jaundice  
1                  You may have Hyperthyroidism  
2     You may have Dimorphic Hemmorhoids(Piles)  
3                     You may have Tuberculosis  
4              You may have Alcoholic Hepatitis  
...                                         ...  
7038              You may have Fungal Infection  
7039                      You may have Migraine  
7040                  You may have Heart Attack  
7041           You may have Peptic Ulcer Diseae  
7042           You may have Alcoholic Hepatitis  

[7043 rows x 2 columns]

In [5]:
import pandas as pd

df['query'] = df['query'].str.replace(r"System:'You are a highly qualified doctor.and chat polietly with patients.'\nPatient:I may have ", '', regex=True)
df['response'] = df['response'].str.replace('You may have ', '', regex=False)

df['query'] = df['query'].str.strip()
df['response'] = df['response'].str.strip()

print(df.head())


                                               query  \
0  itching,vomiting,fatigue,weight_loss,high_feve...   
1  fatigue,weight_loss,restlessness,sweating,diar...   
2  constipation,pain_during_bowel_movements,pain_...   
3  chills,vomiting,fatigue,weight_loss,cough,high...   
4  vomiting,yellowish_skin,abdominal_pain,swellin...   

                       response  
0                      Jaundice  
1               Hyperthyroidism  
2  Dimorphic Hemmorhoids(Piles)  
3                  Tuberculosis  
4           Alcoholic Hepatitis  


In [6]:
df1['Symptoms'] =df1[['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4']].apply(lambda x: ' '.join(x.dropna()), axis=1)

df1 = df1.drop(columns=['Unnamed: 0'])


In [7]:
df1 = df1.drop(columns=['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4'])


In [8]:
df1

Disease  \
0                            Fungal infection   
1                            Fungal infection   
2                            Fungal infection   
3                            Fungal infection   
4                            Fungal infection   
...                                       ...   
4915  (vertigo) Paroymsal  Positional Vertigo   
4916                                     Acne   
4917                  Urinary tract infection   
4918                                Psoriasis   
4919                                 Impetigo   

                                               Symptoms  
0     itching  skin_rash  nodal_skin_eruptions  disc...  
1      skin_rash  nodal_skin_eruptions  dischromic _...  
2     itching  nodal_skin_eruptions  dischromic _pat...  
3               itching  skin_rash  dischromic _patches  
4              itching  skin_rash  nodal_skin_eruptions  
...                                                 ...  
4915     vomiting  headache  nausea  spinning_movements  
4916   skin_rash  pus_filled_pimples  blackheads  sc...  
4917   burning_micturition  bladder_discomfort  foul...  
4918   skin_rash  joint_pain  skin_peeling  silver_l...  
4919   skin_rash  high_fever  blister  red_sore_arou...  

[4920 rows x 2 columns]

In [9]:

df1.rename(columns={'Disease': 'response', 'Symptoms': 'query'}, inplace=True)
df = pd.concat([df, df1], axis=0, ignore_index=True)
print(df.head())


                                               query  \
0  itching,vomiting,fatigue,weight_loss,high_feve...   
1  fatigue,weight_loss,restlessness,sweating,diar...   
2  constipation,pain_during_bowel_movements,pain_...   
3  chills,vomiting,fatigue,weight_loss,cough,high...   
4  vomiting,yellowish_skin,abdominal_pain,swellin...   

                       response  
0                      Jaundice  
1               Hyperthyroidism  
2  Dimorphic Hemmorhoids(Piles)  
3                  Tuberculosis  
4           Alcoholic Hepatitis  


In [10]:
df

query  \
0      itching,vomiting,fatigue,weight_loss,high_feve...   
1      fatigue,weight_loss,restlessness,sweating,diar...   
2      constipation,pain_during_bowel_movements,pain_...   
3      chills,vomiting,fatigue,weight_loss,cough,high...   
4      vomiting,yellowish_skin,abdominal_pain,swellin...   
...                                                  ...   
11958     vomiting  headache  nausea  spinning_movements   
11959   skin_rash  pus_filled_pimples  blackheads  sc...   
11960   burning_micturition  bladder_discomfort  foul...   
11961   skin_rash  joint_pain  skin_peeling  silver_l...   
11962   skin_rash  high_fever  blister  red_sore_arou...   

                                      response  
0                                     Jaundice  
1                              Hyperthyroidism  
2                 Dimorphic Hemmorhoids(Piles)  
3                                 Tuberculosis  
4                          Alcoholic Hepatitis  
...                                        ...  
11958  (vertigo) Paroymsal  Positional Vertigo  
11959                                     Acne  
11960                  Urinary tract infection  
11961                                Psoriasis  
11962                                 Impetigo  

[11963 rows x 2 columns]

In [11]:
x=df['query']

In [12]:
y=df['response']

In [13]:
import re
import nltk
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text(text):

    text = text.replace(',', ' ')
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'_', ' ', text)
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(text)
    filtered_text = [word for word in word_tokens if word not in stop_words]
    lemmatizer = WordNetLemmatizer()
    lemmatized_text = [lemmatizer.lemmatize(word) for word in filtered_text]

    return ' '.join(lemmatized_text)

processed_texts = [preprocess_text(text) for text in x]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(processed_texts)
sequences = tokenizer.texts_to_sequences(processed_texts)
padded_sequences = pad_sequences(sequences, padding='post')

print(padded_sequences)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


[[ 18   3   4 ...   0   0   0]
 [  4  22   5 ...   0   0   0]
 [102   1 116 ...   0   0   0]
 ...
 [ 64  99 138 ...   0   0   0]
 [  2  13  10 ...   0   0   0]
 [  2  13   8 ...   0   0   0]]


In [14]:
processed_texts

['itching vomiting fatigue weight loss high fever yellowish skin dark urine abdominal pain',
 'fatigue weight loss restlessness sweating diarrhoea fast heart rate excessive hunger muscle weakness irritability abnormal menstruation',
 'constipation pain bowel movement pain anal region bloody stool irritation anus',
 'chill vomiting fatigue weight loss cough high fever sweating loss appetite mild fever yellowing eye swelled lymph node malaise phlegm chest pain blood sputum',
 'vomiting yellowish skin abdominal pain swelling stomach distention abdomen history alcohol consumption fluid overload',
 'vomiting breathlessness sweating chest pain',
 'stomach pain acidity ulcer tongue vomiting cough chest pain',
 'skin rash chill joint pain vomiting fatigue high fever headache nausea loss appetite pain behind eye back pain malaise muscle pain red spot body',
 'vomiting headache altered sensorium',
 'burning micturition bladder discomfort continuous feel urine',
 'skin rash high fever blister red

In [15]:
y

0                                       Jaundice
1                                Hyperthyroidism
2                   Dimorphic Hemmorhoids(Piles)
3                                   Tuberculosis
4                            Alcoholic Hepatitis
                          ...                   
11958    (vertigo) Paroymsal  Positional Vertigo
11959                                       Acne
11960                    Urinary tract infection
11961                                  Psoriasis
11962                                   Impetigo
Name: response, Length: 11963, dtype: object

In [16]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

label_encoder = LabelEncoder()

categorical_labels = label_encoder.fit_transform(y)
categorical_labels = to_categorical(categorical_labels)

label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Label Mapping:", label_mapping)
print("Categorical Labels:", categorical_labels)

import pickle

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)



Label Mapping: {'(Vertigo) Paroymsal  Positional Vertigo': 0, '(vertigo) Paroymsal  Positional Vertigo': 1, 'AIDS': 2, 'Abdominal Aortic Aneurysm': 3, 'Acanthosis Nigricans': 4, 'Achalasia': 5, 'Achilles Tendinitis': 6, 'Achilles Tendon Rupture': 7, 'Acl Injury': 8, 'Acne': 9, 'Acoustic Neuroma': 10, 'Acromegaly': 11, 'Actinic Keratosis': 12, 'Acute Coronary Syndrome': 13, 'Acute Flaccid Myelitis': 14, 'Acute Liver Failure': 15, 'Acute Lymphocytic Leukemia': 16, 'Acute Myelogenous Leukemia': 17, 'Acute Sinusitis': 18, 'Addisons Disease': 19, 'Adenomyosis': 20, 'Adhd': 21, 'Adjustment Disorders': 22, 'Adrenal Cancer': 23, 'Adult Adhd': 24, 'Adult Congenital Heart Disease': 25, 'Adult Stills Disease': 26, 'Age Spots': 27, 'Agoraphobia': 28, 'Aids': 29, 'Airplane Ear': 30, 'Albinism': 31, 'Alcohol Intolerance': 32, 'Alcohol Poisoning': 33, 'Alcohol Use Disorder': 34, 'Alcoholic Hepatitis': 35, 'Alcoholic hepatitis': 36, 'Allergies': 37, 'Allergy': 38, 'Alpha Gal Syndrome': 39, 'Alzheimers

In [17]:
categorical_labels.shape[1]

1097

## Model

In [18]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = len(tokenizer.word_index) + 1
embedding_dim = 100
max_length = padded_sequences.shape[1]

from tensorflow.keras.layers import Bidirectional

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length))
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(Bidirectional(LSTM(64, return_sequences=False)))
model.add(Dense(categorical_labels.shape[1], activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:

model.fit(padded_sequences, categorical_labels,batch_size=32 ,epochs=10, validation_split=0.2)


Epoch 1/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 72s 217ms/step - accuracy: 0.0353 - loss: 5.1066 - val_accuracy: 0.1220 - val_loss: 3.7873
Epoch 2/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 72s 239ms/step - accuracy: 0.1960 - loss: 3.6638 - val_accuracy: 0.3422 - val_loss: 2.8329
Epoch 3/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 65s 218ms/step - accuracy: 0.4373 - loss: 2.7657 - val_accuracy: 0.5374 - val_loss: 1.8449
Epoch 4/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 82s 219ms/step - accuracy: 0.6018 - loss: 2.1156 - val_accuracy: 0.5863 - val_loss: 1.3063
Epoch 5/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 65s 218ms/step - accuracy: 0.6578 - loss: 1.7351 - val_accuracy: 0.6348 - val_loss: 1.0112
Epoch 6/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 82s 220ms/step - accuracy: 0.7263 - loss: 1.4333 - val_accuracy: 0.6832 - val_loss: 0.7728
Epoch 7/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 81s 217ms/step - accuracy: 0.7547 - loss: 1.2347 - val_accuracy: 0.7560 - val_loss: 0.5421
Epoch 8/10
300/300 ━━━━━━━━━━━━━━━━━━━━ 82s 218ms/step - accuracy: 0.7864 - loss: 1

## Prediction

In [20]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

def preprocess_new_text(text, tokenizer, max_length):
    processed_text = preprocess_text(text)
    sequence = tokenizer.texts_to_sequences([processed_text])
    padded_sequence = pad_sequences(sequence, maxlen=max_length, padding='post')
    return padded_sequence


new_texts = [
    "Shortness of breath, wheezing, chest tightness, coughing, especially at night"
]


preprocessed_texts = np.vstack([preprocess_new_text(text, tokenizer, max_length) for text in new_texts])

predictions = model.predict(preprocessed_texts)


predicted_classes = np.argmax(predictions, axis=1)
predicted_labels = label_encoder.inverse_transform(predicted_classes)

for text, label in zip(new_texts, predicted_labels):
    print(f"Text: {text}")
    print(f"Predicted Label: {label}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 378ms/step
Text: Shortness of breath, wheezing, chest tightness, coughing, especially at night
Predicted Label: Allergy


In [21]:
import pandas as pd

description = pd.read_csv("description.csv")
diets = pd.read_csv("diets.csv")
medications = pd.read_csv("medications.csv")
precautions_df = pd.read_csv("precautions_df.csv")
merged_df = description.merge(diets, on='Disease', how='outer')\
                       .merge(medications, on='Disease', how='outer')\
                       .merge(precautions_df, on='Disease', how='outer')
merged_df = merged_df.drop(columns=['Unnamed: 0'])

In [22]:
merged_df.fillna("consult doctor",inplace=True)

In [24]:
merged_df.to_csv('merged_df.csv', index=False)


In [25]:
rows = merged_df[merged_df['Disease'].str.contains(label)]
if not rows.empty:
    first_row = rows.iloc[0]
    print("First record found:")
    print(first_row)
else:
    print(f"No records found with the disease 'Diabetes'{label}.")


First record found:
Disease                                                   Allergy
Description     Allergy is an immune system reaction to a subs...
Diet            ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
Medication      ['Antihistamines', 'Decongestants', 'Epinephri...
Precaution_1                                       apply calamine
Precaution_2                              cover area with bandage
Precaution_3                                       consult doctor
Precaution_4                          use ice to compress itching
Name: 1, dtype: object


## Saving Model

In [26]:
import pickle

with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)


In [27]:
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)


In [28]:

import pickle

with open('pad_sequences.pkl', 'wb') as f:
    pickle.dump(pad_sequences, f)


In [29]:
print(f"Pandas version: {pd.__version__}")
import sklearn
print(f"TensorFlow version: {tf.__version__}")
print(f"Scikit-learn version: {sklearn.__version__}")
print(f"Numpy version: {np.__version__}")
print(f"NLTK version: {nltk.__version__}")

Pandas version: 2.1.4
TensorFlow version: 2.17.0
Scikit-learn version: 1.3.2
Numpy version: 1.26.4
NLTK version: 3.8.1
