##Text Generation Model

In [ ]:
data = """History
Before writing essay on Pakistan, lets disucss its history first. Muslims of the subcontinent were not given the proper rights and were harassed for living according to the Islamic way. Pakistan was a dream for Allama Muhammad Iqbal that came true after many sacrifices and struggles of many Muslims.

The major effort and struggle was of Quid e Azam M.A. Jinnah. This effort to get a separate country started when Muslims started facing persecution. The idea of two nation theory was presented that Muslims and Hindus are different nations that can’t live together peacefully.

Quaid e Azam succeeded on 14 Aug 1947 when a new country known as Pakistan was formed. Initially, Bangladesh was a part of Pakistan, but due to the 1971 civil war and political problems, East Pakistan (Bangladesh) proclaimed its independence.

When Pakistan got its independence, it faced several problems, such as unfair boundary distribution, economic problems, the Kashmir dispute, electricity problems, division of financial assets, etc. Karachi was chosen as the capital of Pakistan Quaid e Azam was the first governor-general, and Liaquat Ali Khan was the prime minister.

Climate
Pakistan is one of the lucky countries. It has all four seasons due to the location. Winter is from December to February, spring is from March to May, Summer is from June to September, and retiring monsoon or autumn is from October to November. This season and their time can differ according to the location, as Pakistan has all plains, plateaus, mountains, or hilly areas.

Pakistan has several rivers; the longest is Indus; other rivers are Jhelum, Chenab, Ravi, Sutlej, and Kabul. The amazing thing is that the coastal areas are normally dry and hot, whereas the lowland plains are cooler than coastal areas, and the uplands or Himalayas are much cooler than the plain; this means at the same time, all seasons can be seen in Pakistan.

Region & Demography
Pakistan has a total area of 796,095 square kilometers. Pakistan has a total population of 207.68 million. The capital of Pakistan is Islamabad. Pakistan has 4 provinces, i.e., Punjab, Balochistan, Khyber Pakhtunkhwa, and Sindh. Punjab was given to this province because of Punj (five) and Aab (Water), i.e., land of river. The population of Punjab is 110 million, Balochistan is 12.34 million, Sindh is 47.89 million, and KPK is 35.53 million.

The area of Punjab is a total of 50,362 square kilometers. The area of Balochistan is 347,190 square kilometers. The area of Sindh is 140,914 square kilometers. The area of KPK is 101,741 square kilometers. There are 170 districts in Pakistan. These districts are further divided into tehsil and union councils.

These districts include all the districts in provinces, Azad Kashmir, the capital territory, and Gilgit Baltistan. Pakistan is considered a young nation as the average age is 23.4, and the 104 million population is the age bracket of 25 to 30.

Language & Culture
The national language of Pakistan is Urdu. More than 60 languages are spoken in different areas of Pakistan. The common language in Punjab is Punjabi, whereas in Khyber Pakhtunkhwa, the language spoken is Pashto, and in Sindh and Balochistan, Sindhi and Balochi, respectively. Hindko, Saraiki, Kashmiri, Gujarati, and other languages are spoken in Pakistan.

The culture of Pakistan is based on Islam, and the main reason for having Pakistan as a separate country is to establish the culture of Islam freely. Several festivals and events are important in Pakistan, such as Eid ul Fitr, Eid ul Adha, Ramadan, etc.

Other minorities can also easily celebrate their festivals, such as Christmas, Easter, Holi, Diwali, etc. Let’s talk about different people in provinces.

Punjab: People in Punjab are mostly warm-hearted and loving. Several tribes, clans, or castes have different cultures and traditions. Their culture and dresses are very bright and mix of colors.

Balochistan: This province is considered to be barren lands and deserts and mountains, but this culture has a culture that is full of traditions, art, and craft, as well as embroidery females mostly do these things. These people are known for their festivals and tribes.

Sindh: These people mostly have agricultural lifestyles. These people practice farming and fishing. These people are dominated by Sufis music.

KPK: The people of KPK are mostly Pathans; they are the most hardworking people and always like to know more about their race; they are obsessed with the race.

Economy
Economy is one of the important thing to discuss in this essay on Pakistan. The major sources of livelihood are agriculture, forestry as well as fishing. Pakistan is ranked in 43 of the major economies. Inflation will be approximately 19.87% in 2022. Around one-half of the laborers are doing these activities.

Several crops are the basis of a good economy, such as cotton, tobacco, pulses, chickpeas, sugarcane, wheat, rice, etc. Pakistan doesn’t have many minerals and energy resources. One-eighth of the labor is engaged in the manufacturing of products. The main imports of the nation are petroleum products, machinery, chemicals, fertilizers, etc., whereas the major exports are cotton, ready-made garments, dried fish, rice, leather goods, etc.

Education
Pakistan is one of the countries with great potential for providing education. Education is one of the most important factors in Pakistan. Although education is not up to the mark, many improvements are still being made, and many schools, colleges, and universities are being established.

HEC (Higher Education Commission) is the biggest institute in Pakistan responsible for overseeing, regulating, and accrediting the higher education efforts in Pakistan. The level of education depends on the financial resources and the commitment level of the government; in Pakistan, the resources are limited, and that’s why there are fewer teachers and education-providing facilities. There are a total of 218 universities in Pakistan.

National Symbols
The national symbols of Pakistan are

Markhor (National Animal)
Chukar (National Bird)
Deodar (National Tree)
Jasmine (National Flower)
Allama Muhammad Iqbal (National Poet)
Quaid e Azam (National Hero)
Shalwar Qameez (National Dress)
Hockey (National Sports)
Indus River (National River)
Okra (National Vegetable)
Dolphin (National Aquatic Animal)
Mango (National Fruit)
Conclusion
To conclude essay on Pakistan I would say that Pakistan has faced several challenges since its independence. But on the other hand, Pakistan is rich in culture and has a young population. This population can help Pakistan to become more economically stable and help Pakistan to prosper. This country had been faced several challenges, such as poverty, terrorism, and political instability, and done major improvements in many scenarios.

Pakistan’s strength is its location and size; this country also benefits from foreign aid and receives donations from IMF, World Bank, and the USA, which means that Pakistan has some good international relations. The major weakness of Pakistan is that people lack knowledge in different fields to become a more modernized society. Pakistan also lacks an efficient education system.

There is improper governance, a lack of an efficient education system, and health care problems that can lead to future difficulties for Pakistan. As Pakistan has faced many challenges in history, it can also face any other challenge with faith and strength.

Frequently Asked Questions (FAQs)
How many times has martial law been applied in Pakistan?
In total 4 martial laws have been applied

First: 7th October 1958 (Iskandar Mirza)

Second: 25th March 1969 (Yahya Khan)

Third: 25th July 1997 (Zia ul Haq)

Fourth: 12th October 1999 (Pervaiz Musharraf)

Who was the first president of Pakistan?
The first president was Major General Iskandar Mirza; he was elected on 5th March 1956.

Who was the first Chief of Army Staff in Pakistan?
The first COAS of Pakistan was Lt. General Tikk.
"""

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

## Data Preprocessing

In [ ]:
tk=Tokenizer()

In [ ]:
tk.fit_on_texts([data])

In [ ]:

len(tk.word_index)

548

In [ ]:
input=[]
for se in data.split('\n'):
  sentence=tk.texts_to_sequences([se])[0]

  for i in range(1,len(sentence)):
    input.append(sentence[:i+1])

In [ ]:
input

[[163, 164],
 [163, 164, 62],
 [163, 164, 62, 18],
 [163, 164, 62, 18, 3],
 [163, 164, 62, 18, 3, 165],
 [163, 164, 62, 18, 3, 165, 166],
 [163, 164, 62, 18, 3, 165, 166, 33],
 [163, 164, 62, 18, 3, 165, 166, 33, 61],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4, 1],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4, 1, 167],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4, 1, 167, 90],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4, 1, 167, 90, 91],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4, 1, 167, 90, 91, 92],
 [163, 164, 62, 18, 3, 165, 166, 33, 61, 21, 47, 4, 1, 167, 90, 91, 92, 1],
 [163,
  164,
  62,
  18,
  3,
  165,
  166,
  33,
  61,
  21,
  47,
  4,
  1,
  167,
  90,
  91,
  92,
  1,
  168],
 [163,
  164,
  62,
  18,
  3,
  165,
  166,
  33,
  61,
  21,
  47,
  4,
  1,
  167,
  90,
  91,
  92,
  1,
  168,


In [ ]:
maxlen=max(len(x) for x in input )

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
pad=pad_sequences(input,maxlen=maxlen,padding='pre')

In [ ]:
pad

array([[  0,   0,   0, ...,   0, 163, 164],
       [  0,   0,   0, ..., 163, 164,  62],
       [  0,   0,   0, ..., 164,  62,  18],
       ...,
       [  0,   0,   0, ...,   3,  12, 547],
       [  0,   0,   0, ...,  12, 547,  70],
       [  0,   0,   0, ..., 547,  70, 548]], dtype=int32)

In [ ]:
x=pad[:,:-1]

In [ ]:
y=pad[:,-1]

In [ ]:
x

array([[  0,   0,   0, ...,   0,   0, 163],
       [  0,   0,   0, ...,   0, 163, 164],
       [  0,   0,   0, ..., 163, 164,  62],
       ...,
       [  0,   0,   0, ...,   4,   3,  12],
       [  0,   0,   0, ...,   3,  12, 547],
       [  0,   0,   0, ...,  12, 547,  70]], dtype=int32)

In [ ]:
y

array([164,  62,  18, ..., 547,  70, 548], dtype=int32)

In [ ]:
x.shape

(1225, 77)

In [ ]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=549)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding

## Model Building

In [ ]:
model=Sequential()
model.add(Embedding(549,100,input_length=77))
model.add(SimpleRNN(150))
model.add(Dense(549,activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 77, 100)           54900     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 150)               37650     
                                                                 
 dense_2 (Dense)             (None, 549)               82899     
                                                                 
Total params: 175449 (685.35 KB)
Trainable params: 175449 (685.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x,y,epochs=100)

Epoch 1/100
39/39 [==============================] - 4s 65ms/step - loss: 6.0446 - accuracy: 0.0384
Epoch 2/100
39/39 [==============================] - 2s 47ms/step - loss: 5.6475 - accuracy: 0.0473
Epoch 3/100
39/39 [==============================] - 2s 39ms/step - loss: 5.5448 - accuracy: 0.0490
Epoch 4/100
39/39 [==============================] - 1s 37ms/step - loss: 5.4550 - accuracy: 0.0743
Epoch 5/100
39/39 [==============================] - 1s 37ms/step - loss: 5.2796 - accuracy: 0.1053
Epoch 6/100
39/39 [==============================] - 1s 37ms/step - loss: 4.9790 - accuracy: 0.1388
Epoch 7/100
39/39 [==============================] - 1s 38ms/step - loss: 4.6110 - accuracy: 0.1641
Epoch 8/100
39/39 [==============================] - 1s 37ms/step - loss: 4.1963 - accuracy: 0.2155
Epoch 9/100
39/39 [==============================] - 2s 65ms/step - loss: 3.8676 - accuracy: 0.2906
Epoch 10/100
39/39 [==============================] - 2s 53ms/step - loss: 3.3962 - accuracy: 0.3788

## Prediction

In [ ]:
text="Economy is one"
import numpy as np

for i in range(20):
  token_text = tk.texts_to_sequences([text])[0]

  padded_token_text = pad_sequences([token_text], maxlen=77, padding='pre')
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tk.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)

1/1 [==============================] - 0s 163ms/step
Economy is one of
1/1 [==============================] - 0s 30ms/step
Economy is one of the
1/1 [==============================] - 0s 29ms/step
Economy is one of the important
1/1 [==============================] - 0s 29ms/step
Economy is one of the important thing
1/1 [==============================] - 0s 31ms/step
Economy is one of the important thing to
1/1 [==============================] - 0s 37ms/step
Economy is one of the important thing to discuss
1/1 [==============================] - 0s 43ms/step
Economy is one of the important thing to discuss in
1/1 [==============================] - 0s 27ms/step
Economy is one of the important thing to discuss in this
1/1 [==============================] - 0s 29ms/step
Economy is one of the important thing to discuss in this essay
1/1 [==============================] - 0s 28ms/step
Economy is one of the important thing to discuss in this essay on
1/1 [==============================] - 0s